In [29]:
import numpy as np
matrix = [[0.74496864],[0.81688289],[0.76223718],[0.79366008],[0.73619291], [0.73978974], [0.71965782], [0.73208794], [0.76348267], [0.80329121]]

matrix = np.array(matrix)
print(matrix)

sim = []
i = 0
for x in matrix:
    sim.append((i, x[0]))
    i+=1
    
print(sim)

[[0.74496864]
 [0.81688289]
 [0.76223718]
 [0.79366008]
 [0.73619291]
 [0.73978974]
 [0.71965782]
 [0.73208794]
 [0.76348267]
 [0.80329121]]
[(0, 0.74496864), (1, 0.81688289), (2, 0.76223718), (3, 0.79366008), (4, 0.73619291), (5, 0.73978974), (6, 0.71965782), (7, 0.73208794), (8, 0.76348267), (9, 0.80329121)]


## Bert Mask

In [1]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer


In [2]:
# from_pt는 해당 모델이 기존에는 텐서플로우가 아닌 파이토치로 학습된 모델이었지만 이를 텐서플로우에서 사용하겠단 의미.

model = TFBertForMaskedLM.from_pretrained('klue/bert-base', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

Downloading:   0%|          | 0.00/424M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


Downloading:   0%|          | 0.00/289 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/243k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [3]:
inputs = tokenizer('축구는 정말 재미있는 [MASK]다.', return_tensors='tf')

In [4]:
print(inputs['input_ids']) # 정수인코딩 결과

tf.Tensor([[   2 4713 2259 3944 6001 2259    4  809   18    3]], shape=(1, 10), dtype=int32)


In [5]:
print(inputs['token_type_ids']) # 세그먼트 인코딩 결과

tf.Tensor([[0 0 0 0 0 0 0 0 0 0]], shape=(1, 10), dtype=int32)


In [6]:
print(inputs['attention_mask']) # 어텐션 마스크

tf.Tensor([[1 1 1 1 1 1 1 1 1 1]], shape=(1, 10), dtype=int32)


In [7]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [10]:
pip('잘생긴 현민이는 이쁜 은빈이의 [MASK]이다.')

[{'score': 0.11891059577465057,
  'token': 4200,
  'token_str': '아들',
  'sequence': '잘생긴 현민이는 이쁜 은빈이의 아들 이다.'},
 {'score': 0.11258185654878616,
  'token': 5565,
  'token_str': '동생',
  'sequence': '잘생긴 현민이는 이쁜 은빈이의 동생 이다.'},
 {'score': 0.0790463387966156,
  'token': 900,
  'token_str': '딸',
  'sequence': '잘생긴 현민이는 이쁜 은빈이의 딸 이다.'},
 {'score': 0.048177462071180344,
  'token': 3781,
  'token_str': '모습',
  'sequence': '잘생긴 현민이는 이쁜 은빈이의 모습 이다.'},
 {'score': 0.04052730277180672,
  'token': 4122,
  'token_str': '엄마',
  'sequence': '잘생긴 현민이는 이쁜 은빈이의 엄마 이다.'}]

In [23]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.2562898099422455,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.17284077405929565,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.1110772043466568,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07248972356319427,
  'token': 2186,
  'token_str': 'series',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.07046632468700409,
  'token': 2143,
  'token_str': 'film',
  'sequence': 'the avengers is a really fun film.'}]

## Bert 다음 문장 예측

In [13]:
import tensorflow as tf
from transformers import TFBertForNextSentencePrediction
from transformers import AutoTokenizer

In [15]:
model = TFBertForNextSentencePrediction.from_pretrained('klue/bert-base', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForNextSentencePrediction: ['bert.embeddings.position_ids']
- This IS expected if you are initializing TFBertForNextSentencePrediction from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForNextSentencePrediction from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.


In [16]:
# 이어지는 두 개의 문장
prompt = "2002년 월드컵 축구대회는 일본과 공동으로 개최되었던 세계적인 큰 잔치입니다."
next_sentence = "여행을 가보니 한국의 2002년 월드컵 축구대회의 준비는 완벽했습니다."
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')
encoding

{'input_ids': <tf.Tensor: shape=(1, 44), dtype=int32, numpy=
array([[    2,  5791,  2440,  5339,  4713,  2104,  2124,  2259,  3708,
         2145,  3965,  6233,  4414,  2496,  2359,  2414,  3665, 31221,
         1751,  9900, 12190,    18,     3,  4062,  2069,   543,  2178,
         2209,  3629,  2079,  5791,  2440,  5339,  4713,  2104,  7288,
         3864,  2259,  5537,  2371,  2219,  3606,    18,     3]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 44), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 44), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>}

In [17]:
# 소프트맥스 함수를 지나기 전의 값인 logits을 리턴
logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]

softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print('최종 예측 레이블 :', tf.math.argmax(probs, axis=-1).numpy())
# 이어지면 0, 안이어지면 1

최종 예측 레이블 : [0]


In [18]:
# 상관없는 두 개의 문장
prompt = "2002년 월드컵 축구대회는 일본과 공동으로 개최되었던 세계적인 큰 잔치입니다."
next_sentence = "극장가서 로맨스 영화를 보고싶어요"
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]

softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print('최종 예측 레이블 :', tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [1]
